# -*- coding: utf-8 -*-
"""cyber-analytics-case.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xNhU6boDh1302bbi3qjfkTNUHl1tjfa
"""

import pandas as pd

ativos = pd.read_csv("ativos.csv", sep=";")

vulnerabilidades = pd.read_csv("vulnerabilidades.csv", sep=";")

print("Ativos:", ativos.shape)

print("Vulnerabilidades:", vulnerabilidades.shape)

ativos.head()

vulnerabilidades.head()

ativos["criticidade"].value_counts(dropna=False)

ativos['criticidade_tratada'] = (

    ativos['criticidade']

    .astype(str)

    .str.strip()

    .str.lower()

    .replace({

        'critica': 'Crítica',

        'crítica': 'Crítica',

        'alta': 'Alta',

        'media': 'Média',

        'média': 'Média',

        'baixa': 'Baixa',

        'n/a': 'Não Informado',

        '': 'Não Informado'

    })

)

ativos['criticidade_tratada'].value_counts(dropna=False)

ativos['criticidade_tratada'] = ativos['criticidade_tratada'].replace({'nan': 'Não Informado'})

ativos['criticidade_tratada'].value_counts(dropna=False)

vulnerabilidades['severidade'].value_counts(dropna=False)

vulnerabilidades['severidade_tratada'] = (

    vulnerabilidades['severidade']

    .astype(str)

    .str.strip()

    .str.lower()

    .replace({

        'critica': 'Crítica',

        'crítica': 'Crítica',

        'alta': 'Alta',

        'alto': 'Alta',

        'media': 'Média',

        'média': 'Média',

        'baixa': 'Baixa',

        'n/a': 'Não Informado',

        'nan': 'Não Informado',

        '': 'Não Informado'

    })

)

vulnerabilidades['severidade_tratada'].value_counts(dropna=False)

vulnerabilidades['origem_tratada'] = (

    vulnerabilidades['origem']

    .astype(str)

    .str.strip()

    .replace({

        'CloudSecurity': 'Cloud Security',

        'Cloud-Security': 'Cloud Security'

    }))

vulnerabilidades['origem_tratada'].value_counts(dropna=False)

ativos_validos = set(ativos['ativo_id'])

vulnerabilidades['ativo_inexistente'] = (

    ~vulnerabilidades['ativo_id'].isin(ativos_validos)

).astype(int)

vulnerabilidades['ativo_inexistente'].value_counts()

vulnerabilidades['data_abertura_tratada'] = pd.to_datetime(

    vulnerabilidades['data_abertura'],

    errors='coerce',

    dayfirst=True

)

vulnerabilidades['data_abertura_tratada'].head()

vulnerabilidades['data_invalida'] = (

    vulnerabilidades['data_abertura_tratada']

    .isna()

    .astype(int)

)

vulnerabilidades['data_invalida'].value_counts()

df_risco = vulnerabilidades.merge(

    ativos,

    on="ativo_id",

    how="left"

)
df_risco.shape

df_risco['severidade_tratada'].value_counts()

pd.crosstab(

    df_risco["criticidade_tratada"],

    df_risco["severidade_tratada"]

)

top_ativos = (

    df_risco

    .groupby('ativo_id')

    .size()

    .reset_index(name='qtd_vulnerabilidades')

    .sort_values('qtd_vulnerabilidades', ascending=False)

)

top_ativos.head(10)

top_risco = (

    df_risco[

        df_risco["severidade_tratada"].isin(["Crítica", "Alta"])

    ]

    .groupby(

        ["ativo_id", "sistema", "criticidade_tratada"],

        dropna=False

    )

    .agg(

        qtd_criticas_altas=("vuln_id", "count")

    )

    .reset_index()

    .sort_values("qtd_criticas_altas", ascending=False)

)

top_risco.head(10)

top_risco_atual = (

    df_risco[

        (df_risco["severidade_tratada"].isin(["Crítica", "Alta"])) &

        (df_risco["status"].isin(["Aberta", "Em tratamento"])) &

        (df_risco["ativo_inexistente"] == 0)

    ]

    .groupby(["ativo_id", "sistema", "criticidade_tratada"],dropna=False)

    .agg(qtd_risco_atual=("vuln_id", "count"))

    .reset_index()

    .sort_values("qtd_risco_atual", ascending=False)

)

top_risco_atual.head(10)

peso_criticidade = {

    'Crítica': 4,

    'Alta': 3,

    'Média': 2,

    'Baixa': 1,

    'Não Informado': 0

}

peso_severidade = {

    'Crítica': 4,

    'Alta': 3,

    'Média': 2,

    'Baixa': 1,

    'Não Informado': 0

}

df_risco['peso_criticidade'] = (

    df_risco['criticidade_tratada']

    .map(peso_criticidade)

)

df_risco['peso_severidade'] = (

    df_risco['severidade_tratada']

    .map(peso_severidade)

)

df_risco['risk_score'] = (

    df_risco['peso_criticidade']

    * df_risco['peso_severidade']

)

df_risco[['criticidade_tratada',

          'severidade_tratada',

          'risk_score']].head()

df_risco['risk_score'].value_counts().sort_index()

por partes,

ativos.to_csv(

    "ativos_tratado.csv",

    sep=";",

    index=False

)

vulnerabilidades.to_csv(

    "vulnerabilidades_tratado.csv",

    sep=";",

    index=False

)

df_risco.to_csv(

    "dataset_analitico_risco.csv",

    sep=";",

    index=False

)

print("Arquivos gerados")

ativos.to_csv(

    "ativos_tratado.csv",

    sep=";",

    index=False,

    encoding="utf-8-sig"

)

vulnerabilidades.to_csv(

    "vulnerabilidades_tratado.csv",

    sep=";",

    index=False,

    encoding="utf-8-sig"

)

df_risco.to_csv(

    "dataset_analitico_risco.csv",

    sep=";",

    index=False,

    encoding="utf-8-sig"

)